name: TGL
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
#      - name: Maximize Build Space
#        uses: easimon/maximize-build-space@master
#        with:
#          root-reserve-mb: 512
#          swap-size-mb: 1024
#          remove-dotnet: 'true'
#          remove-android: 'true'
#          remove-haskell: 'true'

      - name: Gitlab Runner
        uses: htilssu/gitlab-runner-action@main
        with:
          server_url: 'https://gitlab2.tgl-cloud.com'
          registration-token: "${{secrets.GITLAB_TGL_REGISTRATION_TOKEN}}"
          docker-image: "docker:29.4.0"
          name: ${{ github.run_id }}
          tag-list: "ci-cd"