name: TGL
on:
  schedule:
    - cron: '0 */23 * * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  runner:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Gitlab Runner
        uses: htilssu/gitlab-runner-action@main
        with:
          server_url: 'https://gitlab2.tgl-cloud.com'
          registration-token: "${{secrets.GITLAB_TGL_REGISTRATION_TOKEN}}"
          docker-image: "docker:29.4.0"
          concurrent: 4
          name: ${{ github.run_id }}
          tag-list: "ci-cd"

  runner_2:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: runner
    steps:
      - name: Gitlab Runner
        uses: htilssu/gitlab-runner-action@main
        with:
          server_url: 'https://gitlab2.tgl-cloud.com'
          registration-token: "${{secrets.GITLAB_TGL_REGISTRATION_TOKEN}}"
          concurrent: 4
          docker-image: "docker:29.4.0"
          name: ${{ github.run_id }}
          tag-list: "ci-cd"

  runner_3:
    needs: runner_2
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Gitlab Runner
        uses: htilssu/gitlab-runner-action@main
        with:
          server_url: 'https://gitlab2.tgl-cloud.com'
          registration-token: "${{secrets.GITLAB_TGL_REGISTRATION_TOKEN}}"
          concurrent: 4
          docker-image: "docker:29.4.0"
          name: ${{ github.run_id }}
          tag-list: "ci-cd"

  runner_4:
    needs: runner_3
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Gitlab Runner
        uses: htilssu/gitlab-runner-action@main
        with:
          server_url: 'https://gitlab2.tgl-cloud.com'
          registration-token: "${{secrets.GITLAB_TGL_REGISTRATION_TOKEN}}"
          concurrent: 4
          docker-image: "docker:29.4.0"
          name: ${{ github.run_id }}
          tag-list: "ci-cd"

  restart:
    needs: runner_4
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1.3.1
        with:
          workflow: 'tgl-sol.yml'
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: 'main'